### ISSUE TITLE
Prometheus の導入

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#108]
本番環境にPrometheusを設定してサーバ監視が出来るようにする。

**Comment by reone19** [comment]
本番環境に直接Prometheusを導入するのですか？
専用のVMを構築するのではなく？

直接Web01に導入すれば、エージェントのネットワークの管理のコスト低いからいいと思いますが、監視ミドルウェアって結構重くないですか？

**Comment by nagi-lc3** [comment]
完了
