### ISSUE TITLE
フロントエンドのVueの環境をCI/CDでビルド管理するかを検討

### ISSUE THREAD

**Issue by reone19** [Kazumasa1/memo-re#114]
フロント側のビルド済み、(もしくは、VM側にvue環境を構築した状態)
の環境をVMにCI/CDを使って自動デプロイを検討する。

@sean-dp の開発リポジトリがforkされたリポジトリではないため確認が必要。

**Comment by nagi-lc3** [comment]
ビルドしたファイルは/usr/share/nginx/htmlディレクトリに配置するようにしてください。

**Comment by nagi-lc3** [comment]
別の方法で完了したので閉じます。
