### ISSUE TITLE
ユーザ検索APIの追加

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#118]
ユーザを検索できるエンドポイントの追加。
仕様については別途考える必要あり。

etc)
username で検索するのか？
user_id で検索するのか？
はたまた両方か？

**Comment by Kazumasa1** [comment]
こちらの[issue](https://github.com/Kazumasa1/memo-re/issues/120)に依存関係あり

**Comment by nagi-lc3** [comment]
もし追加する場合、検索機能にはDRF標準のSearchFilterとdjango-filterパッケージのDjangoFilterBsckendがあります。
前者は検索機能に柔軟性がなく、実用的な使い方には後者のパッケージが必要です。pipでインストールして使用してください。

**Comment by Kazumasa1** [comment]
仕様はこちら。
https://github.com/Kazumasa1/memo-re/issues/120
