### ISSUE TITLE
ユーザ検索機能の仕様を検討する

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#120]
ユーザ検索の際に、既存のフレンドモデルを使うのか、新しくユーザ検索用のモデルを作成するのかなどの検討が必要。
他にも、検索に使うフィールドは？とか色々考えたい。

**Comment by reone19** [comment]
既存のフレンドモデルを使う場合だと、Lineみたいに友達間でクローズな環境でidをお互いに教えあって打ち込む形になると思います。


検索に使うフィールドは？　というのは
既存のフレンドモデルに検索用のフィールドを追加するという事ですか？

フレンドテーブルの`user_to_id`部分だけとユーザテーブルのタグをjoinしたレコードを検索できるようselectすればいいのでは？
と考えました。

意義異論求めます。

**Comment by reone19** [comment]
仮に検索テーブルを作成する場合は

ユーザテーブルとフレンドテーブルと繋げることになりますが
参照整合性制約上、検索テーブルは参照するテーブル先が2つ以上になるので、専用テーブルを作っても検索速度は向上しないと考えます。

逆に遅くなると思う。

**Comment by reone19** [comment]
全体検索はユーザテーブルにするという方針で
discord上でも議論になりましたが
優先的にそこを実装してください。

**Comment by Kazumasa1** [comment]
検索に使うフィールドは`tag`と`username`と`id`？
`tag`っている？

**Comment by Kazumasa1** [comment]
協議の結果、
`username`で検索を行いレスポンスで該当ユーザの`username`, `icon_uri`, `tag`を返すようにする。

`id`や`tag`での検索は余力があれば行う。
