### ISSUE TITLE
AIサーバにドメインを紐づけてhttps化

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#123]
## 手順
1. azure ポータルのdnsでAIサーバのIPにドメイン名を紐づける（ドメイン名はai.xxxx.orgなど）
2. 証明書を取得
3. 証明書紐づけ

**Comment by reone19** [comment]
やるならビルドしたフロントをSCPで移行する前にしましょう。

**Comment by nagi-lc3** [comment]
完了
