### ISSUE TITLE
フロント側でOGPの追加

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#124]
URLを貼った時の画像（OGP）欲しくない？

**Comment by reone19** [comment]
同意はできます。
作ったやつをツイッターに上げるとかは全然ありだと思いますが
優先度は中程度だと思います。
変更を求めます。<`ヘ´>

**Comment by reone19** [comment]
🐵

**Comment by sean-dp** [comment]
一応コードは実装したけどイメージまでの絶対パスがどこになるかよくわかってないからビルドした後動くか確認してほしい。

**Comment by Kazumasa1** [comment]
> 一応コードは実装したけどイメージまでの絶対パスがどこになるかよくわかってないからビルドした後動くか確認してほしい。

それでは変更のマージ後にデプロイして確認できたらclose で！

**Comment by Kazumasa1** [comment]
https://github.com/Kazumasa1/memo-re/pull/211 こちらのPRで完了。
