### ISSUE TITLE
AIサーバのコードをAIディレクトリ以下に入れてソース管理する

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#134]

**Comment by reone19** [comment]
memoreリポジトリのルート配下に
AIディレクトリを作って、Fast APIのコードの中身ぶち込めってことですか？

**Comment by nagi-lc3** [comment]
そう！ソースコードがブラックボックス化されてるの良くないと思うから

**Comment by reone19** [comment]
とりま、不要なデータ削除して、API関連のファイルと画像生成スクリプトだけにまとめました。
プルリクも承認されたのでissuesを閉じたいと考えます。
