### ISSUE TITLE
アカウント情報変更ページでemailとpasswordを変更できないようにする

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#136]
現状のアカウント情報変更ページの仕様は、

- アイコンの変更
- ユーザ名の変更
- タグの変更

だけなので、emailとpasswordを変更できないようにdjoserをオーバーライドする必要がある。

**Comment by reone19** [comment]
パスワード変更画面の作成も必要ですが、機能とレイアウトの実装に関しては現状の作業進捗的に優先度は低くなるので結構後になりそうです。

**Comment by Kazumasa1** [comment]
了解です。エンドポイントとして既に用意されているので、不正値をあらかじめ弾けるようにします。
後々からエンドポイントを用意しなくても良くなりますし。
