### ISSUE TITLE
Djangoを使ってVueの画面を表示できるようにする

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#14]
現在はDjangoとVueのコンテナはできているが別々で実行している。
これをDjangoとVueを連携して表示できるようにしたい。

プルリク先：[setup-django-rest-framework](https://github.com/Kazumasa1/memo-re/tree/feature/setup-django-rest-framework)

参考
     - https://thinkami.hatenablog.com/entry/2022/12/06/232643

**Comment by KleinChiu** [comment]
#13 はもうマージしたし、これは残ったほうがいい？
