### ISSUE TITLE
環境変数を.env化する

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#15]
現在、djangoのシークレットキーやMySQLのキーをそのまま使用しているので.envを使用するように変更する。
djangoのシークレットキーは既にPushされてしまっているので変更するなど留意する。

**Comment by KleinChiu** [comment]
ちなみにだけど、vue用の環境変数はビルドの時点で渡さないと 反映のないので

**Comment by nagi-lc3** [comment]
environ使ったのね。
https://wonderwall.hatenablog.com/entry/2018/04/07/001500
DBのenvについて、必要があればこのサイトを参考にしてください。

これは前に私が作成したDBの設定ファイル
![image](https://user-images.githubusercontent.com/57529474/208035336-0997e955-b646-4849-91fd-abe984ec09d5.png)

**Comment by Kazumasa1** [comment]
https://qiita.com/moonwalkerpoday/items/9da47dda80d3ddac9a62
