### ISSUE TITLE
APIサーバからのレスポンスを高速化

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#155]
現状は遅すぎる。

**Comment by nagi-lc3** [comment]
ローカルでの動作は早かったので、本番環境のCORS設定を無効化して、ローカル環境のフロント（run serve）から一時的に本番apiサーバにAPIリクエストを送ってみた結果、相変わらず遅かった。

よって原因は、本番サーバにあると確定した。
※フロント、バックAPIが原因ではありません。

サーバのスペック、nginx, uwsgi, DB, ネットワーク等が原因である可能性が高い。

**Comment by reone19** [comment]
Azure Database for mysqlのリージョンが速度低下の原因みたいです。
✘East-Asia
○East-Japan
物理的な距離が原因でした。

ごめんなさい。

**Comment by nagi-lc3** [comment]
完了！
