### ISSUE TITLE
PrometheusおよびGrafanaの構築

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#156]

**Comment by reone19** [comment]
Prometheusから作業を進めます（　＾ω＾）・・・

**Comment by Kazumasa1** [comment]
Prometheusの設定ファイルとGrafanaの監視項目ってコード化してる？
できればコード管理してPushしていただきたい。

**Comment by reone19** [comment]
いやだ、マニュアル作るに止めます。

**Comment by Kazumasa1** [comment]
？

**Comment by reone19** [comment]
？？
とりま、余裕あったら、今あるドキュメント整形してコード管理考えます。

**Comment by reone19** [comment]
ソース化の準備します。修正、metricの追加等まだありますが、構築はできたのでcloseします。
