### ISSUE TITLE
ブラウザをリサイズしてもバックグラウンドのJSの領域がリサイズされない

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#161]
ブラウザのサイズを変えるとそれに対応してバックグラウンドのJSの領域も広げたい。
![resize](https://user-images.githubusercontent.com/70145199/212904226-4b1fa31e-9b77-4d27-8f42-de6a9c9c4de0.png)

**Comment by reone19** [comment]
@honjii 
改善できそうですか？

**Comment by sean-dp** [comment]
俺も気になってたんだけど
jQueryとJSのコード見た感じ生成時にしか大きさを計測していないのが原因だと思う
