### ISSUE TITLE
メニューバーのデザイン変更

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#162]
![image](https://user-images.githubusercontent.com/57529474/212909526-64d1d4e9-6bb3-4708-81ac-305c1dad0bbe.png)

日本語がいいと思うのですがいかかでしょうか。
また、アイコンもつけた方が良いと思います。

**Comment by Kazumasa1** [comment]
Duplicate of #164

**Comment by Kazumasa1** [comment]
こちらのissueは#164 と重複しているので、#164 の方を消化してください。
