### ISSUE TITLE
メニューバーのデザイン大幅変更

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#164]
![image](https://user-images.githubusercontent.com/57529474/212910048-19c17a6c-0e6f-4020-85f5-0291345f1fec.png)
現状のプロフィールとクリエイトが同じ階層にあるデザインは絶対におかしい。
難しいと思うけど、なんかいい感じにして欲しい。

**Comment by Kazumasa1** [comment]
項目名を日本語に変更。
ページ遷移する項目としない項目と区切りか何かを追加してわかるようにする。
アイコンは日本語に変更してから様子見。
