### ISSUE TITLE
htmlファイルのlinkに先読み設定を追加して速度改善

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#165]
https://penpen-dev.com/blog/%E3%80%90%E9%81%95%E3%81%84%E3%80%91dns-prefetch%E3%80%81preconnect%E3%80%81prefetch%E3%80%81preload%E3%80%81prerender/

どれを選択するかは分からない。

**Comment by reone19** [comment]
？どれを選択するかはわからないとはどういう意味ででしょうか？

dns-prefetch、preconnect、prefetch、preload、prerender　を使って
従来の[DNS の名前解決] -> [TCP 接続の確立] -> [Fetch] -> [Load] -> [Render]とは別の構成にしろということでしょうか？

うーん、何をすれば良いのかわからないかな。
