### ISSUE TITLE
ロゴにリンク先を追加

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#166]
![image](https://user-images.githubusercontent.com/57529474/212912396-a88ac6a9-4ce4-4127-b528-ab737e7f7495.png)
このロゴです。

**Comment by Kazumasa1** [comment]
indexのリンク？

**Comment by reone19** [comment]
ロゴを押すと、記憶一覧画面に飛ぶのだ！　ｂｙずんだもん
でやらかしているのですが...どうなんでしょう？

**Comment by reone19** [comment]
ロゴを押しても記憶一覧
profileを押しても記憶一覧に飛ぶじゃだめですか？

**Comment by sean-dp** [comment]
実装した！！

**Comment by Kazumasa1** [comment]
https://github.com/Kazumasa1/memo-re/pull/195 で対応したのでクローズ。
