### ISSUE TITLE
フォームのプレースホルダー等に説明が欲しい

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#169]
![image](https://user-images.githubusercontent.com/57529474/212913773-aa94a5b1-4b8f-40ed-b8b3-594e6e1e5c54.png)

![image](https://user-images.githubusercontent.com/57529474/212913905-e0084100-12c1-49e0-bc74-f36eb6cb14e5.png)
入力途中にこれはダメです。みたいな非同期処理？欲しい。

**Comment by reone19** [comment]
HTMLのバリデータチェックとかじゃダメなんですか？
![image](https://user-images.githubusercontent.com/66284670/213450535-c32333f7-7ce9-44d2-99cd-88526ef02014.png)
こんなのとか？

**Comment by Kazumasa1** [comment]
プレースホルダーのみを実装。
