### ISSUE TITLE
キーワードの入力方式変更

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#170]
![image](https://user-images.githubusercontent.com/57529474/212914129-c272f8ab-4e01-4b15-a021-e0ba31362e7f.png)
現状は入力しづらい。せめて, は、にして欲しい。

**Comment by Kazumasa1** [comment]
ここの入力は根本的にユーザビリティが低いので、

1. キーワードをユーザが入力
2. 「追加ボタン？」をクリックでキーワードに追加

など、入力エラーになりにくい設計にする必要がありそう。

**Comment by Yuuma-ujimoto** [comment]
この問題に関しては入力が日本語のみを前提とするならスペースを,にreplaceAllすれば解決する(学内審査の時点ではそうやってた)
英語も使うなら全角スペースのみをreplaceすれば英文が入力されてもある程度は問題なくプロンプトを生成可能
もっと厳格にしたい場合はfor分で１文字づつ判定を行なう必要が出てくると思う

**Comment by sean-dp** [comment]
完了
