### ISSUE TITLE
メニューバーのロゴ変更

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#173]
![image](https://user-images.githubusercontent.com/57529474/212915692-a2640fe7-2050-40ae-84a1-9d1d907d9f7b.png)
ここに置くなら横長の漢字がいいかな。まあ任せる！！

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/213920315-441f4151-6bcd-4e92-a75b-a01ffda2eadc.png)
過去のロゴ候補をスクショしたやつがあったので、のっけておきます。
リンクは知りません・・・ @honjii なら知ってます。

**Comment by honjii** [comment]
<img width="40" alt="スクリーンショット 2023-01-23 0 55 11" src="https://user-images.githubusercontent.com/67584075/213925486-e748a056-fb9e-4905-ab60-4ea631972b0f.png">

**Comment by honjii** [comment]
螺旋丸でいいでしょ

**Comment by Kazumasa1** [comment]
螺旋丸で決定！
