### ISSUE TITLE
全員の作成した記憶一覧画面が欲しいかも

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#174]
どこかに欲しいかも。。。！！！！！！

**Comment by reone19** [comment]
ナビゲーション追加して、そういった画面を見れるようにするのはありですね。

フレンドの記憶詳細が見れる所まで更新されたら、次は共有機能の実装になると思います。
その次は検索の機能の実装とかになります。

ここまで終わったら、実装する感じになると思います。
順序ずらす必要があるならば、調整等検討します。

**Comment by Kazumasa1** [comment]
前ユーザの作成したノートを作成日順で個数を指定して取得できるAPIを追加して実装。
スクロールごとにノートを追加するかは、進捗を見て決定。

**Comment by Kazumasa1** [comment]
バック側でAPIは実装完了しました。

**Comment by sean-dp** [comment]
個数制限はもうかけられてる？
