### ISSUE TITLE
ユーザ情報更新ページの作成

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#179]
バックは既に完成しているのでフロントしことしろ！！

**Comment by honjii** [comment]
<img width="542" alt="スクリーンショット 2023-01-23 0 44 10" src="https://user-images.githubusercontent.com/67584075/213924908-590099d4-7f2f-4ec6-878b-06be1cc78fc9.png">

**Comment by Kazumasa1** [comment]
icon_uriはこれを追加するといい感じになる。
`<form method="post" class="" enctype="multipart/form-data">`

**Comment by Kazumasa1** [comment]
@honjii 
このページで変更できるユーザ情報は、

- ユーザ名
- アイコン画像
- タグ

のみになります。

**Comment by nagi-lc3** [comment]
![image](https://user-images.githubusercontent.com/57529474/214810288-f1393eac-208e-4549-9ff8-a9266338bd86.png)
編集するページに飛ぶリンクはここのフレンド申請の場所がいいかも（twitter参照）

自分のページ（編集）
フレンドのページ（フレンド中？）
未フレンドのページ（フレンド申請）
フレンド申請中のページ（フレンド申請済み）

ところでフレンド申請が来ている状態の時にその相手のページに飛ぶと表示はどうなるの？お互いがフレンド申請を送ることができるの？それともフレンド申請が来ていますと表示させるの？

**Comment by Kazumasa1** [comment]
> お互いがフレンド申請を送ることができるの？

既に一方からフレンド申請がされている場合は、ユニーク制約でエラーになり出来ません。

**Comment by nagi-lc3** [comment]
フロント側はどう表示させるの？
このフレンドから申請が来ていますとフレンド申請の代わりに、相手のページを見た時に表示されるの？

**Comment by sean-dp** [comment]
この画像自体の保存処理ってバックでできてるってことでおけ？
