### ISSUE TITLE
useridのuuid化

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#180]
どうするか検討中

**Comment by reone19** [comment]
@nagi-lc3 
ユーザIDで検索出来るようにしたいということでしょうか？
@Kazumasa1と @honjii で検索画面のレビュ－をした時は

ユーザテーブルのユーザ名、タグで検索しようという話はした気がします。

**Comment by reone19** [comment]
結局どうすることにしましたか？

**Comment by Kazumasa1** [comment]
今回は工数の都合上不採用。
