### ISSUE TITLE
indexページへのリンク追加

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#187]
![image](https://user-images.githubusercontent.com/57529474/212991234-cae857c8-da92-4e83-bf3f-c8d9ebd62c24.png)

![image](https://user-images.githubusercontent.com/57529474/212991313-cf7a3b09-dcd7-4413-bed2-18ee09008fc5.png)
後者はhelp的なリンクでindexに飛ばすとか？

**Comment by Kazumasa1** [comment]
これ @nagi-lc3 くんの認識ではindexページがLP（企画説明のページ）ってことであってる？
サインインのページにも作る必要あるかな？ブラウザバックで確認はできるが戻るボタン的なのを想定してる？

> 後者はhelp的なリンクでindexに飛ばすとか？

これは私もLPが作成できているので、サイドバーかフッターか分かりませんが、LPへのリンクは追加した方がいいと思います。

**Comment by nagi-lc3** [comment]
🐒

**Comment by sean-dp** [comment]
戻るボタンは俺のほうでも考えてた
実装します

**Comment by sean-dp** [comment]
LPってことだったらそこはただの紹介ページだからログイン中は見れなくていいのかなとは思ってる。
サインイン関連には実装したので後ほどpull-riquestします

**Comment by reone19** [comment]
@sean-dp のプルリクエスト承認後にcloseします。
