### ISSUE TITLE
ノート詳細ページのデザイン変更

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#188]
![image](https://user-images.githubusercontent.com/57529474/212993213-826e5b35-dab8-44f1-99b5-86130e94440d.png)
ここダサい！

**Comment by reone19** [comment]
なるほど
改善案とか、提案とかありますか？

**Comment by reone19** [comment]
スライドショーにしても良いかも？

**Comment by honjii** [comment]
下スクロールにして解消
<img width="830" alt="スクリーンショット 2023-01-23 0 42 48" src="https://user-images.githubusercontent.com/67584075/213924849-2b7de974-2ff8-4b4d-84bb-fa9d73b4e342.png">

**Comment by reone19** [comment]
本日の議論対象です。
