### ISSUE TITLE
フッターの追加

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#190]
画面下が少し窮屈に感じます。
フッターなどを追加するのがいいと思います。

<img width="1440" alt="スクリーンショット 2023-01-18 15 43 57" src="https://user-images.githubusercontent.com/70145199/213104163-e3be6831-e7a6-4b8f-9dc9-50f75c70ec79.png">

**Comment by sean-dp** [comment]
サイドメニューがあるからいらないかなとは思ってる。
デザインとも考えてみる。

**Comment by reone19** [comment]
協議した結果フッターは必要ない結論になりました。
