### ISSUE TITLE
フロントの画像配置場所について

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#197]
元々のwebサイトに使われている画像はimg/に置いてください。media/はサイト内で生成された画像やユーザーがアップロードした画像を配置するディレクトリです。

つまり、
media/ -> ai生成画像、ユーザーアップロード画像
img/     -> その他

**Comment by reone19** [comment]
はい。

**Comment by Kazumasa1** [comment]
現在の構成を確認して、大丈夫そうならクローズ。

**Comment by sean-dp** [comment]
対応しました
