### ISSUE TITLE
docker compose up をするとbackディレクトリにmedia とstatic ディレクトリが生成される

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#21]
勝手に中身のないディレクトリが生成されるので、改善したい。

**Comment by Kazumasa1** [comment]
生成されたくないディレクトリ

memo-re/back/
 - media
 - static
 - templates

**Comment by nagi-lc3** [comment]
マイグレーションファイルやAPIドキュメントのymxファイルも生成される。
やっぱりdockerの設定だと思います。

**Comment by Kazumasa1** [comment]
現状、生成されることによる問題はないのでクローズ。
