### ISSUE TITLE
既にフレンドのユーザの場合、フレンド申請ボタンを非表示にする

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#231]
現状だとフレンドのユーザにもフレンド申請ボタンが表示されてしまう。
フレンドチェックエンドポイントを使ってフレンドかどうか確認できるようにしてください。

![スクリーンショット 2023-01-25 23 26 50](https://user-images.githubusercontent.com/70145199/214589273-dbedc72c-bfdc-4b00-a62c-66e39097588b.png)

**Comment by nagi-lc3** [comment]
既にフレンドなら表示させないよりも、”フォロー中（フレンド中？）”みたいな感じの方が分かりやすいと思う。
あとボタンには影を付けたり、ホバーしたら影の濃度が変化するみたいな分かりやすい動きが必要。

**Comment by sean-dp** [comment]
実装したので家に帰ったらプルリクします
