### ISSUE TITLE
ログインユーザのノートをあげる側ともらう側で識別できるようにする

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#232]
狂う狂う

**Comment by reone19** [comment]
モデルの改修ですか？

**Comment by Kazumasa1** [comment]
ぴよぴよ

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/214597625-9353d652-493a-4819-88cb-a752c4ecf937.png)

![image](https://user-images.githubusercontent.com/66284670/214597707-e74a426b-0716-4fd6-9940-acba17635d10.png)
貰うをデフォルト１でモデルを改修しました。

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/214605135-3c1bb265-a5d1-4bd6-9782-300481284e8f.png)
- カラム英語名のdistinction をgetに変えました。
