### ISSUE TITLE
README.md のdocker compose の手順を修正

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#35]
現状のコマンドだと、初回実行時にエラーが発生する。
MySQLのDBが作成された後にDjangoを起動させたいので、

```
docker compose up db --build --no-cache -d
docker compose up  web back --build --no-cache -d
```
などの初回実行時のコマンドを追加する。

**Comment by nagi-lc3** [comment]
https://zenn.dev/daisukesasaki/articles/fab90376b9d4eb
これの1と2を試してみたけどダメだった。
3のシェル試してみて。
