### ISSUE TITLE
Dependabot alertsの修正

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#4]
Dependabot alertsに何件かアラートが出ているので修正してほしい

https://github.com/Kazumasa1/memo-re/security/dependabot

**Comment by KleinChiu** [comment]
![image](https://user-images.githubusercontent.com/65886108/203635427-95b681e8-78b5-4981-a3db-75cfa1bb8c1c.png)
オーナー以外の人は見えないと思う

**Comment by Kazumasa1** [comment]
scrapy の問題はパッチが適用されたバージョンがないので放置
