### ISSUE TITLE
モデル改修案　提案

### ISSUE THREAD

**Issue by reone19** [Kazumasa1/memo-re#66]
ボツ。下の方見てください。

**Comment by reone19** [comment]
自分でレコード抽出して検証してみましたが、これは根本的にボツだと
気づきました。

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/209662742-52d09b53-61b1-4e9f-bb4c-43f0f861d8b0.png)

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/209666220-18522d78-7fc2-44e1-b02a-cefed099f675.png)

こっちが正しいです。
確認してください

変更点

- パスワードがなかったから追加しました
- ユーザテーブルとノート共有テーブルが繋がってたのを不採用にしました
- フレンドテーブルのleftをuseridの外部キーとして持つことにしました。(参照整合性成約によりuseridがフレンドテーブルに存在していないと、テーブル自体が作成できないためです)
- rightカラムを（ユーザ相手）をfriendカラムに改名しました。
- is_deletedカラムのデフォルト値を「0」に指定しました。

**Comment by Kazumasa1** [comment]
確認遅れで申し訳ない！！

何点か提案があります。

**1点目**
フレンドテーブルとノートテーブルにもDATETIME型の登録日がわかるカラムを追加した方がいいと思います。

**2点目**
ノートIDもユーザIDと命名規則を合わせて`noteid`の方がいいと思います。

現状こんな感じです！！

**Comment by reone19** [comment]
いや、他の作業がある中、対応ありがたい。

**１点目**　
それに関しては問題ないです。それを追加することによって、ソート機能を実装しやすくなると思うし、論理削除のカラムが一応あるので、設計的には適切だと考えます。論理削除カラムを使うのが手間ならカラムだけ置いて、物理削除でも行けると思います。※物理削除にする場合、すべてのテーブル作成時にCASCADE
CASCADEにおける物理削除とは、親レコードの1つが削除されると、対応するすべての子レコードが自動的に削除されることを意味します。

逆質問：成約はNotNullの認識で大丈夫ですか？

**2点目**
問題ないです。


以上の点を踏まえて、モデルの編集をこちらがわでしましょうか？

**Comment by reone19** [comment]
![image](https://user-images.githubusercontent.com/66284670/209819988-ecc93039-e4e4-4dff-9595-8c6fdc7bb757.png)
- フレンドテーブルには登録日付カラムを追加
- ノートテーブルには作成日付カラムを追加
- note_idをnoteidカラムに改名しました。
※登録日、作成日のNotNull成約はつけませんでした。プログラミングをする時、そこはnullのままにしないように、自動でタイムスタンプが登録されるようにほっとくことも出来るので、それと、現実問題、論理削除や日付の表示の機能を削減する場合、NotNullだとテーブルをアップデートする工数が増えるのでnull許容のままにしたほうが便利です。

**Comment by Kazumasa1** [comment]
> 逆質問：制約はNotNullの認識ですか？

これに関しては、Null許容でいいんじゃないかな。タイムスタンプ型だったら自動的にインサートしてくれるんだけどね。（DATETIME型で問題ないです）

> 以上の点を踏まえて、モデルの編集をこちらがわでしましょうか？

これは、`models.py` の修正のことかな？まあ、DB設計がこれでほぼほぼ確定するし、バック側で対応するので問題ないです。30日中にはできると思います。

他諸々OKです！

**Comment by reone19** [comment]
わかりました。
ありがとう。

このissueは閉じます。
