### ISSUE TITLE
エラーページの追加

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#70]
現状、存在しないページにアクセスするとnginxのエラー画面になる。
これを404エラーページなど、エラーによって対応するページにする。

**Comment by KleinChiu** [comment]
存在しないページって、なんか例えはある？
404にするより、index.htmlを返したほうがいいとおもう

**Comment by Kazumasa1** [comment]
404ページを表示するサイト
https://github.com/Kazumasa1/a

失敗したメッセージ＆トップページへのリンクを表示するサイト
https://www.amazon.co.jp/gaga

> 404にするより、index.htmlを返したほうがいいとおもう

何も表示しないでそのままindex.htmlに戻せばいいのか。どっちがいいんだろ。

**Comment by nagi-lc3** [comment]
以前はindex.htmlにリダイレクト処理で返してたけど、開発環境ではウザいということで今はコメントアウトしてる。
必要なら存在しないURLを検索した場合に任意のページにリダイレクト処理を行うことはできる。
404とどちらが良いか検討して決めてください。

**Comment by KleinChiu** [comment]
ウェブサイトの遷移は `vue-router` で解決している、
そのため、`index.html` を返して、フロントエンドで遷移失敗ページを表示したほうがいいと思ってる

例えば `/mypage` に直接アクセスするとき、 `index.html` を返さないと、 `vue-router` はマイページに遷移できません
また、エラーページを表示するように設定したら、 アクセスできるはずの `/mypage` は `nginx` のせいで404ページになる

@Yuuma-ujimoto @reone19 どう思う？

**Comment by Kazumasa1** [comment]
画面が増えることになるし・・・
リダイレクトでいい気がする

**Comment by reone19** [comment]
リダイレクトで良いです。失敗したことに対するレスポンス自体は実装しなくて良いです。レイアウト増える手間を考えると工数に含めるのは良くない。
 @Yuuma-ujimoto 確認お願いします。
確認され続けないならこのissueはクローズシていいと思います。

**Comment by Yuuma-ujimoto** [comment]
リダイレクトでいいと思う

**Comment by reone19** [comment]
リダイレクトってことで閉じます。
