### ISSUE TITLE
バックのユーザー認証周りのAPI実装

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#72]
既に実装済みのライブラリ(djoser,django-restframework-JWT)を使う場合、柔軟性に欠けるのでライブラリの設定にフロント側で合わせる必要があります。詳細を閲覧したい場合はライブラリを検索するか、dockerを起動して指定のURLにて、実装済みのAPIドキュメントの閲覧およびテストができるので試してみてください。

すべてを1から作る場合、柔軟性はありますがバックの作業量が増えるかと思います。

作業担当者の作業がやり易い方法を選択してください。話し合いが必要であればここで話し合ってください。

**Comment by Kazumasa1** [comment]
これって`/api/v1/ `問題だよね？
一応確認。

**Comment by nagi-lc3** [comment]
エンドポイントの先頭にapi/v1付けるかに関してもそうだけど、主にユーザー認証にライブラリ使うか否かの問題。ライブラリを使うならエンドポイントは特定のものを使わないといけない。

**Comment by Kazumasa1** [comment]
Uhh...エンドポイントは変えられないためにフロント側と差異が生まれるのか・・・

> 作業担当者の作業がやり易い方法を選択してください。

これは @nagi-lc3 くんは現状どうすればいいと思ってる？

**Comment by nagi-lc3** [comment]
バックでAPI作成に慣れているなら、一から作ってもそんなに時間かからないと思う。逆に慣れていないならライブラリを使った方が柔軟性には欠けるが早いと思う。ただそれをするとフロントにも負荷がかかるのでどっちもどっち。
実際の作業担当者が判断した方が良い。

**Comment by nagi-lc3** [comment]
API部分はあまり詳しくないので分からん！！

**Comment by Kazumasa1** [comment]
> 実際の作業担当者が判断した方が良い。

これは @nagi-lc3 くんでは？？？？？？？？？？？？？

**Comment by nagi-lc3** [comment]
？？？？

**Comment by nagi-lc3** [comment]
私はAPI部分には手を出しません！！

**Comment by reone19** [comment]
バックのユーザー認証周りのAPI実装のissueを上げたのはあなたです。
一番、認証でどれを選び取るべきか議論と提案を生んだあなたがやってください。
命令です。

APIのJWTライブラリ利用を想定した仕様書とモックサーバへの対応。
フロントへの確認周りはサポートします。
