### ISSUE TITLE
dockerでdjangoを立ち上げると出るエラー

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#80]
start.shの3行目のsourceコマンドが効いてないみたいだけどこれは大丈夫なのか？
![image](https://user-images.githubusercontent.com/57529474/210018140-6fcdceba-3441-4d24-929c-95cbfa393105.png)

**Comment by Kazumasa1** [comment]
すまん。そこ消し損ねてた。修正します。

**Comment by Kazumasa1** [comment]
その行必要ないっすね。
