### ISSUE TITLE
django-imagekitのサムネが自動生成されない問題

### ISSUE THREAD

**Issue by nagi-lc3** [Kazumasa1/memo-re#84]
## 概要
本アプリではmodels.pyで画像の整形に本ライブラリを使用している。
詳しくはdjango-imagekitで検索すること。

これはフロント側で画像一覧（AIで生成された画像）ページやそのほかのページで使用するものと思われる。（使わないかもしれないが）

しかし現状、問題が発生している。
python manage.py generateimagesコマンドを実行しないとサムネが生成されない。現在はdockerのstart.shでこのコマンドを実行している。
尚、サムネ画像の生成場所はCACHE/以下である。（設定で変更可能）

本番環境で使用する場合、現状ではエラーが発生してしまうものと思われる。

## 解決方法
コマンドを実行しなくても自動的にサムネが生成されるようにしたい。過去にこのアプリを使用した際は自動的に生成されたはずなので、難しい問題ではないと思う。

## その他
問題解決自体はバック側で行うものではあるが、フロント側でもこのライブラリによって生成されるファイル一覧及び、その利用について確認しておくこと。その上で、必要ないのであれば、その旨をここにコメントしてください。

**Comment by nagi-lc3** [comment]
バック側で画像の整形しないならこのイシューは閉じて構いません。その場合、私に連絡をお願いします。

**Comment by Kazumasa1** [comment]
https://github.com/matthewwithanm/django-imagekit/issues/343
